#ifndef __KEY_EVENT_DEAL_H__
#define __KEY_EVENT_DEAL_H__

#include "typedef.h"
#include "bt_profile_cfg.h"
#include "system/event.h"

enum {
    KEY_POWER_ON = KEY_EVENT_MAX,
    KEY_POWEROFF,
    KEY_POWEROFF_HOLD,
    KEY_MUSIC_PP,
    KEY_MUSIC_PREV,
    KEY_MUSIC_NEXT,
    KEY_VOL_UP,
    KEY_VOL_DOWN,
    KEY_CALL_LAST_NO,
    KEY_CALL_HANG_UP,
    KEY_CALL_ANSWER,
    KEY_CALL_ANSWER_UP,
    KEY_OPEN_SIRI,
    KEY_HID_CONTROL,
    KEY_LOW_LANTECY,
    KEY_MODE_SWITCH,

    KEY_EQ_MODE,
    KEY_THIRD_CLICK,

    KEY_MUSIC_FF,
    KEY_MUSIC_FR,
    KEY_MUSIC_PLAYER_START,
    KEY_MUSIC_PLAYER_END,
    KEY_MUSIC_PLAYER_DEC_ERR,
    KEY_MUSIC_DEVICE_TONE_END,
    KEY_MUSIC_PLAYER_QUIT,
    KEY_MUSIC_PLAYER_AUTO_NEXT,
    KEY_MUSIC_PLAYER_PLAY_FIRST,
    KEY_MUSIC_PLAYER_PLAY_LAST,
    KEY_MUSIC_CHANGE_REPEAT,
    KEY_MUSIC_CHANGE_DEV,
    KEY_MUSIC_AUTO_NEXT_DEV,
    KEY_MUSIC_CHANGE_DEV_REPEAT,
    KEY_MUSIC_SET_PITCH,
    KEY_MUSIC_SET_SPEED,
    KEY_MUSIC_PLAYE_BY_DEV_FILENUM,
    KEY_MUSIC_PLAYE_BY_DEV_SCLUST,
    KEY_MUSIC_PLAYE_BY_DEV_PATH,
    KEY_MUSIC_DELETE_FILE,
    KEY_MUSIC_PLAYE_NEXT_FOLDER,
    KEY_MUSIC_PLAYE_PREV_FOLDER,
    KEY_MUSIC_PLAYE_REC_FOLDER_SWITCH,
    KEY_MUSIC_PLAYER_AB_REPEAT_SWITCH,

    KEY_SEND_SPEECH_START,
    KEY_SEND_SPEECH_STOP,
#if (BT_FOR_APP_EN)
    KEY_AI_DEC_SUSPEND,
    KEY_AI_DEC_RESUME,

#endif

    KEY_EARTCH_ENABLE,
    KEY_EARTCH_DISABLE,
    KEY_ANC_SWITCH,
    KEY_ANC_EAR_ADAPTIVE,
    KEY_ANC_COEFF_SWITCH,
    KEY_MUSIC_EFF,  //播歌音效切换
    KEY_PHONE_PITCH,//通话上行 变声切换
    KEY_HEARING_AID_TOGGLE,//辅听功能开关

    MSG_HALF_SECOND,
    KEY_CLEAN_PHONE_INFO,
    KEY_CLEAN_PHONE_INFO_HOLD,
    KEY_CLEAN_PHONE_INFO_UP,

    KEY_SPATIAL_EFFECT_MODE_SWITCH, /*切换空间音频模式*/
    KEY_NULL = 0xFF,
};

enum {
    ONE_KEY_CTL_NEXT_PREV = 1,
    ONE_KEY_CTL_VOL_UP_DOWN,
};

enum {
    EARTCH_STATE_IN,
    EARTCH_STATE_OUT,
    EARTCH_STATE_TRIM_OK,
    EARTCH_STATE_TRIM_ERR,
};

extern int app_earphone_key_event_handler(struct sys_event *);

#endif
